// ============================================
// db/seeds/movies-data.js — 45 Doraemon theatrical films
// ============================================

const BASE_MOVIES = [
  { id: 1, title_vi: 'Chú khủng long của Nobita', title_jp: 'のび太の恐竜', release_year: 1980, release_date: '15/03/1980', director: 'Hiroshi Fukutomi' },
  { id: 2, title_vi: 'Nobita và lịch sử khai phá vũ trụ', title_jp: 'のび太の宇宙開拓史', release_year: 1981, release_date: '14/03/1981', director: 'Hideo Nishimaki' },
  { id: 3, title_vi: 'Nobita thám hiểm vùng đất mới', title_jp: 'のび太の大魔境', release_year: 1982, release_date: '13/03/1982', director: 'Hideo Nishimaki' },
  { id: 4, title_vi: 'Nobita và lâu đài dưới đáy biển', title_jp: 'のび太の海底鬼岩城', release_year: 1983, release_date: '12/03/1983', director: 'Tsutomu Shibayama' },
  { id: 5, title_vi: 'Nobita và chuyến phiêu lưu vào xứ quỷ', title_jp: 'のび太の魔界大冒険', release_year: 1984, release_date: '17/03/1984', director: 'Tsutomu Shibayama' },
  { id: 6, title_vi: 'Nobita và cuộc chiến vũ trụ', title_jp: 'のび太の宇宙小戦争', release_year: 1985, release_date: '16/03/1985', director: 'Tsutomu Shibayama' },
  { id: 7, title_vi: 'Nobita và binh đoàn người sắt', title_jp: 'のび太と鉄人兵団', release_year: 1986, release_date: '15/03/1986', director: 'Tsutomu Shibayama' },
  { id: 8, title_vi: 'Nobita và hiệp sĩ rồng', title_jp: 'のび太と竜の騎士', release_year: 1987, release_date: '14/03/1987', director: 'Tsutomu Shibayama' },
  { id: 9, title_vi: 'Nobita Tây du kí', title_jp: 'のび太のパラレル西遊記', release_year: 1988, release_date: '12/03/1988', director: 'Tsutomu Shibayama' },
  { id: 10, title_vi: 'Nobita và nước Nhật thời nguyên thủy', title_jp: 'のび太の日本誕生', release_year: 1989, release_date: '11/03/1989', director: 'Tsutomu Shibayama' },
  { id: 11, title_vi: 'Nobita và hành tinh muông thú', title_jp: 'のび太とアニマル惑星', release_year: 1990, release_date: '10/03/1990', director: 'Tsutomu Shibayama' },
  { id: 12, title_vi: 'Nobita ở xứ sở nghìn lẻ một đêm', title_jp: 'のび太のドラビアンナイト', release_year: 1991, release_date: '09/03/1991', director: 'Tsutomu Shibayama' },
  { id: 13, title_vi: 'Nobita và vương quốc trên mây', title_jp: 'のび太と雲の王国', release_year: 1992, release_date: '07/03/1992', director: 'Tsutomu Shibayama' },
  { id: 14, title_vi: 'Nobita và mê cung thiếc', title_jp: 'のび太とブリキの迷宮', release_year: 1993, release_date: '06/03/1993', director: 'Tsutomu Shibayama' },
  { id: 15, title_vi: 'Nobita và ba chàng hiệp sĩ mộng mơ', title_jp: 'のび太と夢幻三剣士', release_year: 1994, release_date: '05/03/1994', director: 'Tsutomu Shibayama' },
  { id: 16, title_vi: 'Đấng toàn năng Nobita', title_jp: 'のび太の創世日記', release_year: 1995, release_date: '04/03/1995', director: 'Tsutomu Shibayama' },
  { id: 17, title_vi: 'Nobita và chuyến tàu tốc hành Ngân Hà', title_jp: 'のび太と銀河超特急', release_year: 1996, release_date: '02/03/1996', director: 'Tsutomu Shibayama' },
  { id: 18, title_vi: 'Nobita và cuộc phiêu lưu ở thành phố dây cót', title_jp: 'のび太のねじ巻き都市冒険記', release_year: 1997, release_date: '08/03/1997', director: 'Tsutomu Shibayama' },
  { id: 19, title_vi: 'Nobita du hành biển phương Nam', title_jp: 'のび太の南海大冒険', release_year: 1998, release_date: '07/03/1998', director: 'Tsutomu Shibayama' },
  { id: 20, title_vi: 'Nobita - Vũ trụ phiêu lưu kí', title_jp: 'のび太の宇宙漂流記', release_year: 1999, release_date: '06/03/1999', director: 'Tsutomu Shibayama' },
  { id: 21, title_vi: 'Nobita và truyền thuyết vua Mặt Trời', title_jp: 'のび太の太陽王伝説', release_year: 2000, release_date: '11/03/2000', director: 'Tsutomu Shibayama' },
  { id: 22, title_vi: 'Nobita và những dũng sĩ có cánh', title_jp: 'のび太と翼の勇者たち', release_year: 2001, release_date: '10/03/2001', director: 'Tsutomu Shibayama' },
  { id: 23, title_vi: 'Nobita và vương quốc robot', title_jp: 'のび太とロボット王国', release_year: 2002, release_date: '09/03/2002', director: 'Tsutomu Shibayama' },
  { id: 24, title_vi: 'Nobita và những pháp sư Gió bí ẩn', title_jp: 'のび太とふしぎ風使い', release_year: 2003, release_date: '08/03/2003', director: 'Tsutomu Shibayama' },
  { id: 25, title_vi: 'Nobita ở vương quốc chó mèo', title_jp: 'のび太のワンニャン時空伝', release_year: 2004, release_date: '06/03/2004', director: 'Tsutomu Shibayama' },
  { id: 26, title_vi: 'Chú khủng long của Nobita 2006', title_jp: 'のび太の恐竜2006', release_year: 2006, release_date: '04/03/2006', director: 'Ayumu Watanabe' },
  { id: 27, title_vi: 'Nobita và chuyến phiêu lưu vào xứ quỷ - 7 dũng sĩ phép thuật', title_jp: 'のび太の新魔界大冒険〜7人の魔法使い〜', release_year: 2007, release_date: '10/03/2007', director: 'Yukiyo Teramoto' },
  { id: 28, title_vi: 'Nobita và người khổng lồ xanh', title_jp: 'のび太と緑の巨人伝', release_year: 2008, release_date: '08/03/2008', director: 'Ayumu Watanabe' },
  { id: 29, title_vi: 'Nobita và lịch sử khai phá vũ trụ (Remake)', title_jp: '新・のび太の宇宙開拓史', release_year: 2009, release_date: '07/03/2009', director: 'Shigeo Koshi' },
  { id: 30, title_vi: 'Nobita và cuộc đại thủy chiến ở xứ sở người cá', title_jp: 'のび太の人魚大海戦', release_year: 2010, release_date: '06/03/2010', director: 'Kozo Kusuba' },
  { id: 31, title_vi: 'Nobita và binh đoàn người sắt - Đôi cánh thiên thần', title_jp: '新・のび太と鉄人兵団〜はばたけ 天使たち〜', release_year: 2011, release_date: '05/03/2011', director: 'Yukiyo Teramoto' },
  { id: 32, title_vi: 'Nobita và hòn đảo diệu kì - Cuộc phiêu lưu của loài thú', title_jp: 'のび太と奇跡の島〜アニマル アドベンチャー〜', release_year: 2012, release_date: '03/03/2012', director: 'Kozo Kusuba' },
  { id: 33, title_vi: 'Nobita và viện bảo tàng bảo bối', title_jp: 'のび太のひみつ道具博物館', release_year: 2013, release_date: '09/03/2013', director: 'Yukiyo Teramoto' },
  { id: 34, title_vi: 'Tân • Nobita thám hiểm vùng đất mới - Peko và 5 nhà thám hiểm', title_jp: '新・のび太の大魔境〜ペコと5人の探検隊〜', release_year: 2014, release_date: '08/03/2014', director: 'Shinnosuke Yakuwa' },
  { id: 35, title_vi: 'Nobita và những hiệp sĩ không gian', title_jp: 'のび太の宇宙英雄記', release_year: 2015, release_date: '07/03/2015', director: 'Yoshihiro Osugi' },
  { id: 36, title_vi: 'Nobita và nước Nhật thời nguyên thủy (Remake)', title_jp: '新・のび太の日本誕生', release_year: 2016, release_date: '05/03/2016', director: 'Shinnosuke Yakuwa' },
  { id: 37, title_vi: 'Nobita và chuyến thám hiểm Nam Cực Kachi Kochi', title_jp: 'のび太の南極カチコチ大冒険', release_year: 2017, release_date: '04/03/2017', director: 'Atsushi Takahashi' },
  { id: 38, title_vi: 'Nobita và đảo giấu vàng', title_jp: 'のび太の宝島', release_year: 2018, release_date: '03/03/2018', director: 'Kazuaki Imai' },
  { id: 39, title_vi: 'Nobita và Mặt Trăng phiêu lưu ký', title_jp: 'のび太の月面探査記', release_year: 2019, release_date: '01/03/2019', director: 'Shinnosuke Yakuwa' },
  { id: 40, title_vi: 'Nobita và những bạn khủng long mới', title_jp: 'のび太の新恐竜', release_year: 2020, release_date: '07/08/2020', director: 'Kazuaki Imai' },
  { id: 41, title_vi: 'Nobita và cuộc chiến vũ trụ tí hon 2021', title_jp: 'のび太の宇宙小戦争2021', release_year: 2022, release_date: '04/03/2022', director: 'Shin Yamaguchi' },
  { id: 42, title_vi: 'Nobita và vùng đất lý tưởng trên bầu trời', title_jp: 'のび太と空の理想郷', release_year: 2023, release_date: '03/03/2023', director: 'Takumi Dohi' },
  { id: 43, title_vi: 'Nobita và bản giao hưởng Địa Cầu', title_jp: 'のび太の地球交響楽', release_year: 2024, release_date: '01/03/2024', director: 'Yukiyo Teramoto' },
  { id: 44, title_vi: 'Nobita và cuộc phiêu lưu vào thế giới trong tranh', title_jp: 'のび太の絵世界物語', release_year: 2025, release_date: '07/03/2025', director: 'Yukiyo Teramoto' },
  { id: 45, title_vi: 'Nobita và lâu đài dưới đáy biển (Phiên bản mới)', title_jp: '新・のび太の海底鬼岩城', release_year: 2026, release_date: '27/02/2026', director: 'Tetsuo Yajima' },
];

const FEATURED_IDS = new Set([1, 5, 10, 26, 38, 43, 44, 45]);

const EXTRA = {
  1: { trailer_url: null, wiki_url: 'https://en.wikipedia.org/wiki/Doraemon:_Nobita%27s_Dinosaur', streaming_url: null, plot: 'Chuyến phiêu lưu kì thú của nhóm bạn tại Bắc Mĩ ở kỷ Creta và nhiệm vụ cứu Pisuke khỏi bọn săn khủng long đến từ tương lai.', box_office: '¥1.56 tỷ' },
  2: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Cuộc đấu tranh của nhóm bạn Nobita và người dân Hành tinh Tím với bọn Hành tinh Đen và bè lũ Xoxi đầu bạc.', box_office: '¥1.75 tỷ' },
  3: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Chuyến thám hiểm châu Phi của cả nhóm cùng chú chó Peko (Bụng Rỗng) bí ẩn.', box_office: '¥1.22 tỷ' },
  4: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Một chuyến phiêu lưu khác của cả nhóm xuống đáy biển và biết được sự tồn tại của một Vương quốc ở đây (Atlantic).', box_office: '¥1.03 tỷ' },
  5: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Cuộc chiến đấu của cả nhóm với thế lực đen tối ở Thế giới phép thuật.', box_office: '¥1.65 tỷ' },
  6: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nhóm bạn tham gia vào một cuộc chiến tranh vũ trụ của những người tí hon.', box_office: '¥1.20 tỷ' },
  7: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Cuộc chiến của nhóm bạn với binh đoàn robot đến từ vũ trụ.', box_office: '¥1.30 tỷ' },
  8: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Chuyến thám hiểm của cả nhóm dưới lòng đất, cùng chứng kiến khoảnh khắc loài khủng long bị tuyệt chủng vào 65 triệu năm trước.', box_office: '¥1.50 tỷ' },
  9: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Chuyến phiêu lưu diệt trừ yêu quái của nhóm bạn. Bộ phim được lấy cảm hứng từ Tây du ký, một tác phẩm kinh điển của văn học Trung Quốc.', box_office: '¥1.36 tỷ' },
  10: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Hành trình quay ngược thời gian trở về thời cổ đại của nhóm bạn (thời đồ đá).', box_office: '¥2.02 tỷ' },
  11: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nhóm bạn Nobita du hành đến Hành tinh muông thú và tham gia một cuộc chiến đấu với bọn xâm lược Nimuge.', box_office: '¥1.91 tỷ' },
  12: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Shizuka bị mất tích và các bạn còn lại đã đi vào một cuộc phiêu lưu đầy sóng gió để tìm cô bé. Bộ phim được lấy cảm hứng từ bộ truyện Nghìn lẻ một đêm.', box_office: '¥1.80 tỷ' },
  13: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nhóm bạn Nobita ngăn chặn được kế hoạch tẩy rửa Địa cầu của những người ở Vương quốc trên mây.', box_office: '¥1.68 tỷ' },
  14: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nhóm bạn đến hành tinh Bliki để chiến đấu với bọn robot nổi loạn ở nơi đây.', box_office: '¥1.65 tỷ' },
  15: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Cả nhóm đã đến thời Trung cổ và trở thành những hiệp sĩ bằng chiếc máy tạo giấc mơ.', box_office: '¥1.35 tỷ' },
  16: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Cuộc phiêu lưu thú vị của nhóm bạn vào thế giới côn trùng dưới lòng đất, trong một không gian mô phỏng của bộ mô hình vũ trụ.', box_office: '¥1.30 tỷ' },
  17: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Chuyến du lịch ngoài vũ trụ qua nhiều hành tinh khác nhau và cuộc chiến đấu với bọn Yadori của nhóm bạn.', box_office: '¥1.65 tỷ' },
  18: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nhóm bạn Doraemon đã gây dựng một hành tinh gồm toàn thú nhồi bông và sau đó là cuộc chiến bảo vệ hành tinh non trẻ.', box_office: '¥2.00 tỷ' },
  19: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Chuyến thám hiểm đi tìm kho báu trên con tàu cướp biển của những thế kỷ trước của các nhân vật.', box_office: '¥2.10 tỷ' },
  20: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Cuộc phiêu lưu vũ trụ đầy trắc trở của các nhóm bạn Doraemon trên con tàu của một chủng tộc người sống lưu vong ngoài vũ trụ.', box_office: '¥2.00 tỷ' },
  21: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Một cuộc du hành xuyên thời gian và không gian đưa cả nhóm đến với nền văn minh Maya cổ đại ở Nam Mỹ.', box_office: '¥3.05 tỷ' },
  22: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Chuyến khám phá thế giới loài chim đầy kì thú của nhóm bạn.', box_office: '¥3.00 tỷ' },
  23: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Câu chuyện về cuộc phiêu lưu của nhóm bạn đến xứ sở robot xa xôi và đầy trắc trở.', box_office: '¥2.31 tỷ' },
  24: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nhóm Doraemon đến với Vương quốc gió và diệt trừ con rồng bí ẩn nơi đây.', box_office: '¥2.54 tỷ' },
  25: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Tình bạn xuyên thời gian, không gian, chủng loài giữa Nobita và Ichi (Số Một) cùng cuộc đấu tranh chống thế lực xấu xa đang tồn tại ở thế giới chó mèo.', box_office: '¥3.05 tỷ' },
  26: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nội dung làm lại từ phim điện ảnh đầu tiên Chú khủng long của Nobita (1980).', box_office: '¥3.28 tỷ' },
  27: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nội dung làm lại từ phim điện ảnh thứ 5 Nobita và chuyến phiêu lưu vào xứ quỷ (1984).', box_office: '¥3.54 tỷ' },
  28: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Một phi thuyền kì lạ kéo nhóm bạn Nobita và Kibo lên Hành tinh Cây; họ phải tìm mọi cách để ngăn cản kế hoạch phủ xanh toàn bộ bề mặt Trái Đất của những người thủ lĩnh nơi đây.', box_office: '¥3.37 tỷ' },
  29: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nội dung làm lại từ phim điện ảnh thứ 2 Nobita và lịch sử khai phá vũ trụ (1981).', box_office: '¥2.45 tỷ' },
  30: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Một chuyến phiêu lưu tình cờ của nhóm bạn đến Vương quốc người cá và tham gia một trận chiến gây cấn ở đấy để giành lại thanh kiếm thần, vật hộ mệnh cho cả vương quốc.', box_office: '¥3.16 tỷ' },
  31: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nội dung làm lại từ phim điện ảnh thứ 7 Nobita và binh đoàn người sắt (1986).', box_office: '¥2.46 tỷ' },
  32: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Bộ phim kỉ niệm 100 năm trước khi Doraemon ra đời, với nội dung là một chuyến phiêu lưu của những người bạn đến hòn đảo diệu kì, nơi tái sinh những động vật đã bị tuyệt chủng từ thời xưa.', box_office: '¥3.62 tỷ' },
  33: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Hành trình truy tìm chiếc chuông bị mất của Doraemon đầy gian nan tại Viện bảo tàng bảo bối tương lai.', box_office: '¥3.98 tỷ' },
  34: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nội dung làm lại từ phim điện ảnh thứ 3 Nobita thám hiểm vùng đất mới (1982).', box_office: '¥3.58 tỷ' },
  35: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nhóm bạn Nobita hóa thân thành những siêu anh hùng vũ trụ để cứu hành tinh Pokkoru khỏi bọn hải tặc vũ trụ.', box_office: '¥3.93 tỷ' },
  36: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Nội dung làm lại từ phim điện ảnh thứ 10 Nobita và nước Nhật thời nguyên thủy (1989).', box_office: '¥4.12 tỷ' },
  37: { trailer_url: null, wiki_url: null, streaming_url: null, plot: 'Hành trình ngược thời gian đến Nam Cực 100.000 năm trước để khám phá bí ẩn chiếc vòng màu vàng bị chôn vùi trong lớp băng tuyết.', box_office: '¥4.43 tỷ' },
  38: { trailer_url: 'xMEDN7jLTpU', wiki_url: 'https://en.wikipedia.org/wiki/Doraemon:_Nobita%27s_Treasure_Island', streaming_url: 'https://www.bilibili.tv/vi', plot: 'Nobita lập đội hải tặc và dấn thân vào hòn đảo kho báu bí ẩn, nơi anh gặp Fio và phát hiện âm mưu đe dọa hành tinh.', box_office: '¥5.37 tỷ' },
  39: { trailer_url: 'V0mKFGVnN0A', wiki_url: 'https://en.wikipedia.org/wiki/Doraemon:_Nobita%27s_Chronicle_of_the_Moon_Exploration', streaming_url: null, plot: 'Nobita khám phá mặt trăng bằng bảo bối và gặp Lucis — mở ra bí mật về nền văn minh ẩn giấu phía sau vẻ đẹp của Mặt Trăng.', box_office: '¥5.02 tỷ' },
  40: { trailer_url: 'qOW-fJJm_GU', wiki_url: 'https://en.wikipedia.org/wiki/Doraemon:_Nobita%27s_New_Dinosaur', streaming_url: null, plot: 'Nobita nuôi hai khủng long song sinh và cùng chúng phiêu lưu qua thời gian để bảo vệ sự sống trước thảm họa diệt vong.', box_office: '¥3.35 tỷ' },
  41: { trailer_url: 'GgDrE1_9yJM', wiki_url: 'https://en.wikipedia.org/wiki/Doraemon:_Nobita%27s_Little_Star_Wars_2021', streaming_url: null, plot: 'Phiên bản làm lại năm 2022: Nobita và Papi — hoàng tử hành tinh tí hon — đối đầu với quân đội tàn bạo đe dọa hòa bình vũ trụ.', box_office: '¥2.69 tỷ' },
  42: { trailer_url: 'pT-3IgCNgHE', wiki_url: 'https://en.wikipedia.org/wiki/Doraemon:_Nobita%27s_Sky_Utopia', streaming_url: null, plot: 'Nhóm bạn bay lên thành phố trên mây Parapara, nơi được quảng cáo là thiên đường lý tưởng nhưng ẩn chứa sự thật đáng sợ.', box_office: '¥4.34 tỷ' },
  43: { trailer_url: 'N8lB6UX0IDo', wiki_url: 'https://en.wikipedia.org/wiki/Doraemon:_Nobita%27s_Earth_Symphony', streaming_url: null, plot: 'Âm nhạc trên Trái Đất biến mất. Nobita và Doraemon hợp tác với Miria để khôi phục giai điệu và cứu hành tinh khỏi sự im lặng.', box_office: '¥4.27 tỷ' },
  44: { trailer_url: 'kYv9N8mXW3A', wiki_url: 'https://en.wikipedia.org/wiki/Doraemon:_Nobita%27s_Art_World_Tales', streaming_url: null, plot: 'Hành trình cùng công chúa Claire đi vào thế giới trong tranh để trở về Công quốc Artoria thuộc châu Âu thời Trung Cổ, giải mã sự mất tích bí ẩn của công chúa và giải cứu thế giới khỏi sự hủy diệt sắc màu.', box_office: '¥4.68 tỷ' },
  45: { trailer_url: 'KDGuBlhrqjg', wiki_url: 'https://doraemon.fandom.com/wiki/Doraemon:_Shin_Nobita_no_Kaitei_Kiganjo', streaming_url: null, plot: 'Nội dung làm lại từ phim điện ảnh thứ 4, kể về chuyến phiêu lưu cắm trại dưới đáy biển của nhóm bạn Nobita, khám phá liên bang Mu và đối đầu hiểm họa từ lâu đài Poseidon.', box_office: '¥4.00 tỷ' },
};

function getMoviesSeedData() {
  return BASE_MOVIES.map((m) => {
    const extra = EXTRA[m.id] || {};
    return {
      ...m,
      plot: extra.plot,
      box_office: extra.box_office,
      image_url: '/assets/images/movies/poster.svg',
      trailer_url: extra.trailer_url ?? null,
      wiki_url: extra.wiki_url ?? null,
      streaming_url: extra.streaming_url ?? null,
      theme_song: `Nhạc phim ${m.title_vi}`,
      is_featured: FEATURED_IDS.has(m.id) ? 1 : 0,
    };
  });
}

module.exports = { getMoviesSeedData, BASE_MOVIES, FEATURED_IDS };
